unit VSM.Model.RetornoJson;

{*******************************************************************************
    Generated By   : JsonToDelphiClass - 0.65
    Project link   : https://github.com/PKGeorgiev/Delphi-JsonToDelphiClass
    Generated On   : 2019-11-18 15:29:53

    Created By     : Petar Georgiev - (http://pgeorgiev.com)
    Adapted Web By : Marlon Nardi - (http://jsontodelphi.com)
*******************************************************************************}

interface

uses Generics.Collections, Rest.Json, uVSMAtributos;

type

TVSMRetornoJson = class(TVSMTabela)
private
  FDescricao: String;
  FTipo: String;
  FTitulo: String;
public
  property descricao: String read FDescricao write FDescricao;
  property tipo: String read FTipo write FTipo;
  property titulo: String read FTitulo write FTitulo;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TVSMRetornoJson;
end;

implementation

{TVSMRetornoJson}


function TVSMRetornoJson.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TVSMRetornoJson.FromJsonString(AJsonString: string): TVSMRetornoJson;
begin
  result := TJson.JsonToObject<TVSMRetornoJson>(AJsonString)
end;

end.
